spring:
  application:
    name: ebay-app
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:dbuser}:${MONGO_PASSWORD:dbpassword}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/ebay-app?retryWrites=false
      max:
        connection:
          idle:
            time: 0

  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none

app:
  ebay:
    base-url: https://api.ebay.com
    auth-path: /identity/v1/oauth2/token
    search-path: /buy/browse/v1/item_summary/search
    item-path: /buy/browse/v1/item
    client-id: ${EBAY_CLIENT_ID}
    client-secret: ${EBAY_CLIENT_SECRET}
  cex:
    base-url: https://wss2.cex.uk.webuy.io
    search-path: /v3/boxes
  telegram:
    base-url: https://api.telegram.org
    message-path: /bot${TELEGRAM_BOT_API_KEY}/sendMessage
    main-channel-id: ${TELEGRAM_CHANNEL_ID}
    secondary-channel-id: ${TELEGRAM_SECONDARY_CHANNEL_ID}

logging:
  pattern:
    console: '%-5level %clr(%msg%n)'
