spring:
  application:
    name: ebay-app
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:dbuser}:${MONGO_PASSWORD:dbpassword}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/catalogue

app:
  ebay:
    base-url: https://api.ebay.com
    auth-path: /identity/v1/oauth2/token
    search-path: /buy/browse/v1/item_summary/search
    item-path: /buy/browse/v1/item
    client-id: ${EBAY_CLIENT_ID}
    client-secret: ${EBAY_CLIENT_SECRET}
  cex:
    base-url: https://wss2.cex.uk.webuy.io
    search-path: /v3/boxes/predictivesearch
